### ISSUE TITLE
Skokie, I've FOIA'd

### ISSUE THREAD

**Issue by sxmchxn** [jjarmoc/chicago-area-general-orders#6]

**Comment by tqbf** [comment]
Excellent! 

Skokie's FOIA contact is FOIA@skokie.org.

It'd be neighborly to check and make sure Skokie's General Orders aren't already online (I think Jeff looked a bit; I haven't). 

Here's an email template: 

```
Subject: Open Records Request re: Police General Orders

Hello! I went looking for this online and couldn't find it, so:

Pursuant to 5 ILCS 140/1, the Illinois Freedom of Information Act, I'm
writing to request the following information:

A complete copy of the General Orders of the [CITY/TOWN/VILLAGE OF WHATEVER].

Please send this information electronically.

I am requesting this information as an individual, for personal and
not commercial use.

Please direct questions about this request to the following email address:

MY@EMAIL

Per 5 ILCS 140/3, I look forward to your timely response to this
request. Thanks in advance for this.

Sincerely,
MY CONTACT INFORMATION

```

By statute, they have 5 days to respond. Let us know when you mail them! If they don't respond or push back, we can help coordinate a response. I had to engage an attorney to get Oak Park's General Orders, it was not at all difficult, and we can probably make arrangements for Skokie as well.

**Comment by jjarmoc** [comment]
I definitely haven’t seen anything for Skokie, so filing sounds right. Thanks for the help! Let us know when you submit so we can start counting down. :)

**Comment by sxmchxn** [comment]
Just sent!

**Comment by sxmchxn** [comment]
I've got a request confirmation from Skokie.

**Comment by sxmchxn** [comment]
They need some more time:

Dear Requester:



This email is in response to your recent request, Request Number: 717-2020
<http://url2602.justfoia.com/ls/click?upn=XfJvxk0gd1RbNAoCtqw15iK2ORNNmoC3FdvkL5LtTEtVBVf9r1INdbT6JCepf45WZfWe3-2BY8UnQsB9agN5VkcszBYmlTw3g-2BWqjVXzUlTH1pwiIfH363HIRWl-2FVDSURizkMcXf-2FPoA8V61N-2FtdMvJQ-3D-3DpjfI_hx8pX06rOU6tgOS6eRaWFnUJcHqBAbZhaxkTjeuNo3duA4TNsj1mz2ARJ3a9K-2FsUAqRoeyUXwj-2FUn-2B0GMKVbaJRySLUsKzEToFDYPa9R3CWizSq8J2kVx32pSKpS5HI840evVhLqgQv0FKZwzxcntRPvBJgSIVvnEl-2BfyR22IwzEZ9G3irheOHZXxgEecKyK-2FeUXZZu5CSrkL3-2FVro6L64VbsYUFENJgtrbc-2BQ0sQjxq18LS1nYEaT7GD-2F-2FRWXKkzodSr0KCqhf9ebWltadkLAkIW5e2jGunufrvflBQI04j5gMaJzJRmaaERzPEgRaM>
made
under the Freedom of Information Act. Due to your request totaling over
1,200 pages, I am notifying you that I will be extending the response date.
Section 3(d) of the Freedom of Information Act provides that the five-day
response period may be extended for up to five additional working days for
a limited number of reasons.  Specifically:

Subsection 3(e)(i) states that the response time period may be extended if
“the requested records are stored in whole or in part at other locations
than the office having charge of the requested records”

Subsection 3(e)(ii) states that the response time period may be extended if
“the request requires the collection of a substantial number of specified
records”.

Pursuant to Subsections 3(e)(i) and 3(e)(ii) we are notifying you of the
Village’s intent to extend the time needed to research your request an
additional five days.  Your FOIA request will be completed no later than
November 25, 2020.



Sincerely,

Alex Franz

Freedom of Information Officer

847/933-8219

**Comment by sxmchxn** [comment]
I just got the pdf response. I don't seem to have write access to push a
branch, how do you want me to get the file into the repo? The link from the
email is *here
<http://url4102.request.justfoia.com/ls/click?upn=XfJvxk0gd1RbNAoCtqw15iK2ORNNmoC3FdvkL5LtTEvTU1-2FZmkmmVfwKF3tN5zUDMITUXQzyIRT2e-2BAfrZdTJkAB9DXaunTKY3l9RaNqygFqau61GwtyaReiV2rrhj96pvddLJT26Stbtsn7aV52pw-3D-3DtDbe_hx8pX06rOU6tgOS6eRaWFnUJcHqBAbZhaxkTjeuNo3duA4TNsj1mz2ARJ3a9K-2FsUAqRoeyUXwj-2FUn-2B0GMKVbaPcp4jtOH2bQtKJR19-2FQxoTbO91CX5cahoH8Zh8G1p79JcorT5ROqjHam6RXi3U3RX6Ftq8KXxr-2BTpr1xKBvFVwxVU4I9qfXJ1v5zLhntmY0GiHDvksT9X8Bf1nyJ69T-2F1zgKi6lxXzaokwfWzqtKdaOIHcVkaiMPN-2FSFy348LQrfFNB38mxhgM9-2B7YKTMmk4hdrazwCvbfSrNZTBcPbpsDYs-2FlKovn0VmwNU8GZbGPc>.*

**Comment by jjarmoc** [comment]
Thanks, @sxmchxn!  

Typically, you'd want to fork my repository, make your changes, and submit a pull request. I can just go ahead and pull the file in though. Look for it to go live in the next couple minutes.

Thanks again for your contribution!
